### PR TITLE
[MODFISTO-260] Tests to demonstrate issues with parallel processing

### PR DESCRIPTION
**Pull request by damien-git**
## Purpose
[MODFISTO-260](https://issues.folio.org/browse/MODFISTO-260) - Transaction summaries are not designed to be used in parallel

## Approach
* Modified `TestBase.java` to add a parameter specifying the number of threads to use to run a test
* Created 3 new tests that demonstrate issues with parallel processing, including the one explained at MODFISTO-260 (there could be others).
* Errors can vary from one execution to another, but all 3 tests reliably fail every time on my machine
* Issues are particularly bad because sometimes no error is reported but the budget is wrong afterwards

### CODE REVIEW

**Comment by AndreiMPV** [comment]
image

**Comment by AndreiMPV** [comment]
image

**Comment by damien-git** [comment]
Screenshot_20220124_132124

**Comment by damien-git** [comment]
This [new PR](https://github.com/folio-org/folio-integration-tests/pull/1242) includes these tests. Closing.

**Pull request closed without merging**
