### PR TITLE
[FAT-2407]-fix ledger-totals

### PR DESCRIPTION
**Pull request by SinghAdes**

### CODE REVIEW

**Comment by SinghAdes** [comment]
image

**Comment by Abdulkhakimov** [comment]
Hi @SinghAdes Was there any change in the calculation logic? If yes. Could you provide link to changes. Thank you!

**Comment by SinghAdes** [comment]
> Hi @SinghAdes Was there any change in the calculation logic? If yes. Could you provide link to changes? Thank you!

Hi @Abdulkhakimov:- There is no change in calculation logic , The APIs are working as expected. for example ..
https://github.com/folio-org/folio-integration-tests/blob/master/acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-totals.feature#:~:text=%7CfundId3%20%20%20%7C,%7C%2032%20%20%20%20%7C  
Expected Allocation To should be 63 but it was given as 0 .

**Comment by Abdulkhakimov** [comment]
> > Hi @SinghAdes Was there any change in the calculation logic? If yes. Could you provide link to changes? Thank you!
> 
> Hi @Abdulkhakimov:- There is no change in calculation logic , The APIs are working as expected. for example .. https://github.com/folio-org/folio-integration-tests/blob/master/acquisitions/src/main/resources/thunderjet/mod-finance/features/ledger-totals.feature#:~:text=%7CfundId3%20%20%20%7C,%7C%2032%20%20%20%20%7C Expected Allocation To should be 63 but it was given as 0 .

Got it. Thanks

**Review by Abdulkhakimov — APPROVED** [review]

**Review by SerhiiNosko — APPROVED** [review]

**Pull request merged**
